### ISSUE TITLE
[Bug]: Wrong behavior when used from the Docker Image

### ISSUE THREAD

**Issue by ladrians** [zilliztech/GPTCache#379]
### Current Behavior

I am following the doc to be used with docker from [here](https://github.com/zilliztech/GPTCache/tree/main/examples#how-to-use-gptcache-server).

I noticed that no matter what Prompt I set, it always returns the 1st item inserted, for example

```
curl -X GET  "http://localhost:8000?prompt=hello"
null
curl -X PUT -d "receive a hello message" "http://localhost:8000?prompt=hello+world"
curl -X GET  "http://localhost:8000?prompt=hello"
"receive a hello message"
curl -X GET  "http://localhost:8000?prompt=bye"
"receive a hello message"
```

I expect that the last `bye` query will not return any value, just a null.

I created a sample `gptcache.yml` with the following

```
model_src:
    openai
...
config:
    similarity_threshold: 0.2
```

By the way if I use `threshold` (as detailed in the docs) I got an error. Then another error using the `-f gptcache.yml` parameter

```
Traceback (most recent call last):
  File "/usr/local/bin/gptcache_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/gptcache_server/server.py", line 55, in main
    init_similar_cache_from_config(config_dir=args.cache_config_file)
  File "/usr/local/lib/python3.8/site-packages/gptcache/adapter/api.py", line 167, in init_similar_cache_from_config
    with open(config_dir, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'gptcache.yml'
```

Modified the command to something like this as I am using Windows and with the volume got it running

```
docker run -p 8000:8000 -v %cd%:"/workspace":rw -it zilliz/gptcache:latest gptcache_server -s 0.0.0.0 -p 8000 -f gptcache.yml
```

I expected to get a better result lowering the `similarity_threshold` value but exactly the same.

Am I missing something in how the component should be used?

thanks!
 

### Environment

```markdown
Windows 10 + Docker Image.
```

**Comment by SimFG** [comment]
Thanks your feedback, I will checkout it!

**Comment by SimFG** [comment]
@ladrians For the first question, I used the latest image, it seems that this problem has not been reproduced. You can try to delete the container and use the latest image to start a new container.
![image](https://github.com/zilliztech/GPTCache/assets/21985684/9f49361e-cff3-4e68-a761-cd5ef6c2cc3f)
For the second question, you can try to enter the container and try to find the `gptcache.yml` file. If you find it, you can try to use the absolute path in the container. If not, you need to confirm whether the local file and docker container path mapping are valid.

**Comment by SimFG** [comment]
The idea abut logging some docker information is great. 
But I have a little doubt now, the problem you encounter now is: 
> I expected to get a better result lowering the similarity_threshold value but exactly the same.

It means that in multiple similar question caches, you hope to get a more random answer. do i understand? If yes, you can try to change the config file.  change the `get_prompt` to the `temperature_softmax`, like:
```
pre_function:
    get_prompt
```
->
```
pre_function:
    temperature_softmax
```

If the response does not address your question, please inform me by providing a simple and detailed example.

**Comment by ladrians** [comment]
No, I just wanted to use it as a semantic search cache. By default expected not to modify any parameter and check and thats why started this ticket.

No idea why your behavior is correct, anyway I tried to use

```
pre_function:
    temperature_softmax
```
and got this error
```
Traceback (most recent call last):
  File "/usr/local/bin/gptcache_server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/gptcache_server/server.py", line 55, in main
    init_similar_cache_from_config(config_dir=args.cache_config_file)
  File "/usr/local/lib/python3.8/site-packages/gptcache/adapter/api.py", line 192, in init_similar_cache_from_config
    pre_func = _get_pre_func(pre_prcocess)
  File "/usr/local/lib/python3.8/site-packages/gptcache/adapter/api.py", line 253, in _get_pre_func
    return getattr(gptcache.processor.pre, pre_prcocess)
AttributeError: module 'gptcache.processor.pre' has no attribute 'temperature_softmax'
```
Am I missing something?

**Comment by SimFG** [comment]
sorry, it's my typo, it should be `post_function`, like:
```
post_function:
    temperature_softmax
```

**Comment by SimFG** [comment]
If your problem isn't solved, perhaps you can give me a video by the discord and I will try to reproduce it according to your video.

**Comment by ladrians** [comment]
Wait do not close it yet, I found that if I query more complex sentences it still does not work.
For example these are some sample questions which I expect not to get a reply and it does return the first cached value

```
Do you know anything about programming?
Show me some programming samples
What is your best programming language?
what programming styles do you know about?
```
On the log file I see
```
PUT /?prompt=Do%20you%20know%20anything%20about%20programming%3F HTTP/1.1" 200 -
GET /?prompt=Show%20me%20some%20programming%20samples HTTP/1.1" 200 -
GET /?prompt=What%20is%20your%20best%20programming%20language%3F HTTP/1.1" 200 -
GET /?prompt=what%20programming%20styles%20do%20you%20know%20about%3F HTTP/1.1" 200 -
```

**Comment by SimFG** [comment]
@ladrians Because there is only a data in the cache, if there are some data in the cache, it will be returned randomly. You can try to put multiple pieces of similar data into it.

**Comment by ladrians** [comment]
I did but for some questions I do not expect to return the cached value and it does. To put it simple, for the 4 questions I cached it returns the initial cached value for the 1st question, so it is not useful. Are you agree with me?

**Comment by SimFG** [comment]
@ladrians yes, sometimes, the cache value is invalid, because it's similar, not exact match. So when you are not satisfied with the cache value, you can re-request llm, and then put the return value in the cache.

**Comment by ladrians** [comment]
ok not sure what I am doing wrong. Noticed the python interface has several tweaks I can change, but using as a service behing a docker image there is not much I can do to change behavior. It is expected to evolve this interface to be used from other languages? It would be nice to have
* logging
* support for different sessions or tenant
* API to handle sessions
* better tweaking of parameters, rather than the yaml file.

**Comment by SimFG** [comment]
thank you so much for your suggestion!!! Currently no other languages are supported, because many features cannot be supported #175. Currently service is a very simple version, more content needs more time to design. At present, we will also make more adjustments based on your suggestions to make it more user-friendly.

And If your question has been solved, please help me close the issue. :>
