### ISSUE TITLE
[Feature]: LangChainChat does work with _agenerate function - 'coroutine' object has no attribute 'llm_output'

### ISSUE THREAD

**Issue by alabrashJr** [zilliztech/GPTCache#400]
### Current Behavior

```python
from langchain.chat_models import ChatOpenAI
from gptcache import cache
from gptcache.adapter.langchain_models import LangChainChat
from langchain.vectorstores import Milvus
from langchain.chains.qa_with_sources import load_qa_with_sources_chain
from langchain.vectorstores.base import VectorStoreRetriever
from langchain.chains import ConversationalRetrievalChain 
import asyncio

def get_msg(data, **_):
    return data.get("messages")[-1].content


cache.init(
    pre_embedding_func=get_msg,
)

chat = LangChainChat(chat=ChatOpenAI(openai_api_key='sk-'))
doc_chain = load_qa_with_sources_chain(chat, chain_type=chain_type, verbose=True)
m = Milvus()
retriever = VectorStoreRetriever(vectorstore=m)
self.chain = ConversationalRetrievalChain(
    retriever=retriever,
    combine_docs_chain=doc_chain,
    return_source_documents=True,
    verbose=True
)
rs = asyncio.run(chain.acall({"question":"who's Justin"}))

```

### Expected Behavior

```
2023-06-01 15:01:27.228 Uncaught app exception
Traceback (most recent call last):
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File ...
    rs = asyncio.run(chain.acall({"question":'who's Justin'}))
  File "/Users/abc/opt/anaconda3/envs/research/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/abc/opt/anaconda3/envs/research/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/abc/prj/src/main/pipeline.py", line 233, in amilvus_retrieval_chatgpt_ct
    result = await self.chain.acall(
  File "/Users/../prj/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 180, in acall
    raise e
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 174, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/conversational_retrieval/base.py", line 142, in _acall
    answer = await self.combine_docs_chain.arun(
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 262, in arun
    return (await self.acall(kwargs, callbacks=callbacks))[self.output_keys[0]]
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 180, in acall
    raise e
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 174, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/combine_documents/base.py", line 99, in _acall
    output, extra_return_dict = await self.acombine_docs(
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/combine_documents/map_rerank.py", line 114, in acombine_docs
    results = await self.llm_chain.aapply_and_parse(
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 273, in aapply_and_parse
    result = await self.aapply(input_list, callbacks=callbacks)
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 177, in aapply
    raise e
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 174, in aapply
    response = await self.agenerate(input_list, run_manager=run_manager)
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 90, in agenerate
    return await self.llm.agenerate_prompt(
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chat_models/base.py", line 149, in agenerate_prompt
    return await self.agenerate(prompt_messages, stop=stop, callbacks=callbacks)
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chat_models/base.py", line 127, in agenerate
    llm_output = self._combine_llm_outputs([res.llm_output for res in results])
  File "/Users/abc/prj/venv/lib/python3.9/site-packages/langchain/chat_models/base.py", line 127, in <listcomp>
    llm_output = self._combine_llm_outputs([res.llm_output for res in results])
AttributeError: 'coroutine' object has no attribute 'llm_output'
```

**Comment by alabrashJr** [comment]
it works btw

```python
rs = chain.call({"question":"who's Justin"})
```

**Comment by alabrashJr** [comment]
Yeah, I just opened the issue so people know that

**Comment by SimFG** [comment]
If you use the langchain, and langchain has supported, the GPTCache would support. However, the AruzeChatComplete is not implemented separately

**Comment by alabrashJr** [comment]
A solution has been provided at https://github.com/zilliztech/GPTCache/pull/408.

**Comment by SimFG** [comment]
it has been fixed in the next version
