### ISSUE TITLE
[Bug]: openai.to_embeddings does not function correctly

### ISSUE THREAD

**Issue by Adam-Gibbs** [zilliztech/GPTCache#403]
### Current Behavior

With the following code:
``` python
from gptcache.embedding import OpenAI
openaiEmbedding = OpenAI()
data_manager = get_data_manager(CacheBase("postgresql", sql_url=os.getenv("DATABASE_URL")), VectorBase("faiss", dimension=openaiEmbedding.dimension))
cache.init(
    embedding_func=openaiEmbedding.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
    pre_embedding_func=get_prompt,
)
```
After trying to get completly different requests it returns the same cached instance
I have tried short one word requests, long requests, complete gibberish and all returns the same response as whatever was first requested

### Expected Behavior

I would expect to see only relevant cached queries being returned, this is the behaviour I see with onnx.to_embeddings, but I am not able to run computationally intensive tasks on my infrastructure, hence why I want to offload to openai.

### Steps To Reproduce

```markdown
Setup the cache as I have set out above, try asking the cache for many different things, notice they all return the same response. This is the completion method I call, I am using streamed responses.

from gptcache.adapter import openai
openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=message,
        stream=True,
    )
```

### Environment

```markdown
Currently this is bing run as a flask server hosted on [railway.app](https://railway.app/) - so I don't have much control over the environment and would prefer to keep the CPU overhead down.
```

### Anything else?

My requirements.txt file if of any use:

```env
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile
#
absl-py==1.4.0
    # via
    #   chex
    #   optax
    #   orbax-checkpoint
aiohttp==3.8.4
    # via openai
aiosignal==1.3.1
    # via aiohttp
async-timeout==4.0.2
    # via aiohttp
attrs==23.1.0
    # via aiohttp
blinker==1.6.2
    # via flask
cached-property==1.5.2
    # via orbax-checkpoint
cachetools==5.3.1
    # via gptcache
certifi==2023.5.7
    # via requests
charset-normalizer==3.1.0
    # via
    #   aiohttp
    #   requests
chex==0.1.7
    # via optax
click==8.1.3
    # via flask
dm-tree==0.1.8
    # via chex
etils==1.3.0
    # via orbax-checkpoint
flask==2.3.2
    # via -r requirements.in
flax==0.6.10
    # via -r requirements.in
frozenlist==1.3.3
    # via
    #   aiohttp
    #   aiosignal
gptcache==0.1.28
    # via -r requirements.in
idna==3.4
    # via
    #   requests
    #   yarl
importlib-resources==5.12.0
    # via orbax-checkpoint
itsdangerous==2.1.2
    # via flask
jax==0.4.11
    # via
    #   chex
    #   flax
    #   optax
    #   orbax-checkpoint
jaxlib==0.4.11
    # via
    #   chex
    #   optax
    #   orbax-checkpoint
jinja2==3.1.2
    # via flask
markdown-it-py==2.2.0
    # via rich
markupsafe==2.1.2
    # via
    #   jinja2
    #   werkzeug
mdurl==0.1.2
    # via markdown-it-py
ml-dtypes==0.1.0
    # via
    #   jax
    #   jaxlib
msgpack==1.0.5
    # via
    #   flax
    #   orbax-checkpoint
multidict==6.0.4
    # via
    #   aiohttp
    #   yarl
nest-asyncio==1.5.6
    # via orbax-checkpoint
numpy==1.24.3
    # via
    #   chex
    #   flax
    #   gptcache
    #   jax
    #   jaxlib
    #   ml-dtypes
    #   opt-einsum
    #   optax
    #   orbax-checkpoint
    #   scipy
    #   tensorstore
openai==0.27.7
    # via -r requirements.in
opt-einsum==3.3.0
    # via jax
optax==0.1.5
    # via flax
orbax-checkpoint==0.2.4
    # via flax
psycopg2==2.9.6
    # via -r requirements.in
pygments==2.15.1
    # via rich
python-dotenv==1.0.0
    # via -r requirements.in
pyyaml==6.0
    # via
    #   flax
    #   orbax-checkpoint
requests==2.31.0
    # via
    #   gptcache
    #   openai
rich==13.4.1
    # via flax
scipy==1.10.1
    # via
    #   jax
    #   jaxlib
tensorstore==0.1.37
    # via
    #   flax
    #   orbax-checkpoint
toolz==0.12.0
    # via chex
tqdm==4.65.0
    # via openai
typing-extensions==4.6.2
    # via
    #   chex
    #   flax
    #   orbax-checkpoint
urllib3==2.0.2
    # via requests
waitress==2.1.2
    # via -r requirements.in
werkzeug==2.3.4
    # via flask
yarl==1.9.2
    # via aiohttp
```

**Comment by Adam-Gibbs** [comment]
Any help would be much appreciated, I have hit a brick wall currently. Thanks in advance

**Comment by SimFG** [comment]
Can you give me your inputs? And I will check it

**Comment by Adam-Gibbs** [comment]
When I run it locally the openai.to_embeddings causes this error when I run it, that does not appear when I use Onnx locally:

``` python
Traceback (most recent call last):
  File "/home/adam/.local/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/adam/.local/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/adam/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adam/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adam/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adam/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adam/Code/makemea/project-duckbill-cache/main.py", line 28, in generateQuestions
    response = get_ai_response(message, prompt)
  File "/home/adam/Code/makemea/project-duckbill-cache/ai.py", line 38, in get_ai_response
    response = openai.ChatCompletion.create(
  File "/home/adam/.local/lib/python3.10/site-packages/gptcache/adapter/openai.py", line 89, in create
    return adapt(
  File "/home/adam/.local/lib/python3.10/site-packages/gptcache/adapter/adapter.py", line 59, in adapt
    cache_data_list = time_cal(
  File "/home/adam/.local/lib/python3.10/site-packages/gptcache/utils/time.py", line 9, in inner
    res = func(*args, **kwargs)
  File "/home/adam/.local/lib/python3.10/site-packages/gptcache/manager/data_manager.py", line 319, in search
    return self.v.search(data=embedding_data, top_k=top_k)
  File "/home/adam/.local/lib/python3.10/site-packages/gptcache/manager/vector_data/faiss.py", line 45, in search
    dist, ids = self._index.search(np_data, top_k)
  File "/home/adam/.local/lib/python3.10/site-packages/faiss/class_wrappers.py", line 329, in replacement_search
    assert d == self.d
AssertionError
```

**Comment by SimFG** [comment]
@Adam-Gibbs you need to delete the cache file, including the `faiss.index` and `sqlite.db`

**Comment by Adam-Gibbs** [comment]
> @Adam-Gibbs you need to delete the cache file, including the `faiss.index` and `sqlite.db`

Thank you that has fixed the local env, now I have tested the issue of the embeddings responding with only cached content happens locally too

**Comment by SimFG** [comment]
I think the wrong cache is caused the openai embedding model. there is my test code.
```
from openai.embeddings_utils import get_embedding, cosine_similarity

a = "Summarise the US Constitution"
b = "How to bake a Cake?"

a_embedding = get_embedding(a, engine='text-embedding-ada-002')
b_embedding = get_embedding(b, engine='text-embedding-ada-002')
print(cosine_similarity(a_embedding, b_embedding))
```
![image](https://github.com/zilliztech/GPTCache/assets/21985684/c60229bf-e28f-49a6-b129-b06a90d152e3)
The range of this value is [-1, 1], the larger the more similar

**Comment by Adam-Gibbs** [comment]
My apologies, what does this mean for my implementation?

**Comment by SimFG** [comment]
In other words, the features extracted by the embedding model from these two sentences are relatively similar, so it is natural to think that the two sentences are relatively similar, which is why the cache considers them to be similar.

**Comment by Adam-Gibbs** [comment]
Ah, so my issue is further down the chain. After some testing modifying the max_distance for SearchDistanceEvaluation and tune my responses. For reference of future people, this gives roughly similar functionality:

``` python
cache.init(
    ...
    similarity_evaluation=SearchDistanceEvaluation(max_distance=1.0)
)
```

However for my uses I prefer a more discerning cache so I am using 0.8
