### ISSUE TITLE
[Bug]: Returns list but expected is str

### ISSUE THREAD

**Issue by eswarthammana** [zilliztech/GPTCache#622]
### Current Behavior

python 3.11
Langhian 0.1.14
gptcache 0.1.43

Following is the example i am trying 
```
llm = LlamaCpp(
    model_path=llm_model_path,
    verbose=True
)

question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"

llm_cache = Cache()
llm_cache.init(
    pre_embedding_func=get_prompt,
    post_process_messages_func=postnop,
)

cached_llm = LangChainLLMs(llm=llm)
answer = cached_llm(question, cache_obj=llm_cache)
```
this gives exception as shown below
 
``` 
Traceback (most recent call last):
  File "C:\xxxx\AI\llmcache\test1.py", line 36, in <module>
    answer = cached_llm(question, cache_obj=llm_cache)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\gptcache\adapter\langchain_models.py", line 121, in __call__
    self.generate([prompt], stop=stop, callbacks=callbacks, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\gptcache\adapter\langchain_models.py", line 100, in generate
    return super().generate(prompts, stop=stop, callbacks=callbacks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\llms.py", line 748, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\llms.py", line 606, in _generate_helper
    raise e
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\llms.py", line 593, in _generate_helper
    self._generate(
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\language_models\llms.py", line 1213, in _generate
    generations.append([Generation(text=text)])
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
```

this is happening because inside adpaters, langchain_models ..
```
def _cache_data_convert(cache_data):
    return cache_data
```
this returns list where as llms.py _generate function expects Generation.text as str

**Comment by SimFG** [comment]
you can try to use the inner langchain cache. refer to: https://github.com/zilliztech/GPTCache/issues/585#issuecomment-1972720103

**Comment by eswarthammana** [comment]
Thanks
